### ISSUE TITLE
Missed a couple resources

### ISSUE THREAD

**Issue by hrbrmstr** [DyfanJones/RAthena#10]
- [{awsathena}](https://github.com/hrbrmstr/awsathena) : rJava Interface to AWS Athena SDK
- [{metis}](https://github.com/hrbrmstr/metis) : Helpers for Accessing and Querying Amazon Athena using R, Including a lightweight RJDBC shim
- [{metisjars}](https://github.com/hrbrmstr/metis-jars) : JARs for ^^
- [{metis.tidy}](https://github.com/hrbrmstr/metis-tidy) : Access and Query Amazon Athena via the Tidyverse

They're used in production every day to analyze petabytes of internet scan and honeypot data.

**Comment by DyfanJones** [comment]
Hi @hrbrmstr  thanks for bring this to my attention. I will add these onto the **Similar Projects** section of the readme documentation.

**Comment by DyfanJones** [comment]
@hrbrmstr  are you happy with the following:

----
  - `awsathena` - rJava Interface to AWS Athena SDK <https://github.com/hrbrmstr/awsathena>
  - `metis` - Helpers for Accessing and Querying Amazon Athena using R, Including a lightweight RJDBC shim <https://github.com/hrbrmstr/metis>
  - `metisjars` - JARs for `metis` <https://github.com/hrbrmstr/metis-jars>
  - `metis.tidy` - Access and Query Amazon Athena via the Tidyverse <https://github.com/hrbrmstr/metis-tidy>
  
`awsathena` and `metis` family of packages are currently used in production every day to analyze petabytes of internet scan and honeypot data.

----

I made a slight change to your last statement to give the packages you have just highlighted more credit.
