### ISSUE TITLE
`tbl(con, "table")` fails with a single column source table

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/RAthena#32]
### Issue Description
Setting up a connection to an Athena 'table' with just one column with tidyverse's tbl-function fails with the error:
>  Error in .valueClassTest(ans, "data.frame", "dbFetch") : 
>   invalid value from generic function ‘dbFetch’, class “factor”, expected “data.frame”

### Reproducible Example
  ```r
library(RAthena)
library(DBI)
con <- dbConnect(RAthena::athena(),
                 profile_name = "rathena")

tttt <- data.frame(a = sample(LETTERS, 5))
copy_to(con, tttt, name = "test")
tbl(con, "test")
```
The tbl-command gives an error:

>  Error in .valueClassTest(ans, "data.frame", "dbFetch") : 
>   invalid value from generic function ‘dbFetch’, class “factor”, expected “data.frame”

The error seems to be triggered at line 149 in Result.R:
https://github.com/DyfanJones/RAthena/blob/460b80e58214f7a2dccf9441e6c39d0b7b98bce5/R/Result.R#L149

So maybe an issue with boto3?

In any case, to get things working, I commented out the whole block dealing with the case n>= 0 etc.
Surely this one is here for a reason, so a better solution would be needed, but nothing to offer for that at the moment.

**Comment by DyfanJones** [comment]
is there an error when your run it through `dbGetQuery`?

i.e. 

```
library(DBI)

con <- dbConnect(RAthena::athena())

dbGetQuery(con, "select * from test")
```

**Comment by DyfanJones** [comment]
@OssiLehtinen found the error, thanks for pointing this out. The error happens when I translate matrix format to data.frame and then remove the first line from the matrix.

```
issue example:
data.frame(a = "A")[-1,]
```
I will have a little think in how to get around this issue

**Comment by OssiLehtinen** [comment]
OK, great!

One option could be to do: `dplyr::filter(data.frame(a = "A"), dplyr::row_number() > 1)`, right?

**Comment by DyfanJones** [comment]
@OssiLehtinen i would like not to have another dependency. As `data.table` is an already existing dependency then a solution through data table would be preferred

**Comment by DyfanJones** [comment]
@OssiLehtinen can you please check branch `dbFetch` to see if bug has been fixed.

**Comment by DyfanJones** [comment]
Merged branch `dbFetch` into master. I will close this issue, if the bug persists your end please feel free to re-open issue :)

**Comment by OssiLehtinen** [comment]
The bug does not persist!

**Comment by DyfanJones** [comment]
I will push these changes to the cran for the weekend. In the mean time if you find anything or any other features to add. Please let me know
