### ISSUE TITLE
Column names with special chacaters produce errors with copy_to

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/RAthena#35]
### Issue Description

 If column names in a data.frame contain special characters, such as 'ä' and 'ö', copy_to fails with the error

> Error: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:8: no viable alternative at input 'CREATE EXTERNAL'

 
### Reproducible Example

  ```r
library(RAthena)
library(DBI)
con <- dbConnect(RAthena::athena(),
                 profile_name = "rathena")

oddcolnames <- data.frame(tämänimi = 1:5)
a_t <- copy_to(cona, oddcolnames, "test")

```

This can be fixed by replacing line https://github.com/DyfanJones/RAthena/blob/48c01bdcdbe5bbf467f1715eee7d06c515bed843/R/table.R#L360

with

> paste0("\`", field_names, "\`", " ", field.types)

**Comment by DyfanJones** [comment]
hi @OssiLehtinen nice spot. Will fix that now

**Comment by DyfanJones** [comment]
@OssiLehtinen sorry for the delay, I have fixed the issue. `dbQuoteIdentifier` now uses Athena quotations. This allows special characters in column and table names. closing this ticket and going to the run tests on pull request: https://github.com/DyfanJones/RAthena/pull/34 to get these features in RAthena
