### ISSUE TITLE
as.integer is translated to cast(col as INT), which does not work

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/RAthena#42]
### Issue Description
The new sql translations seem to have an error with integers. Using as.integer results in

> Error: SYNTAX_ERROR: line 1:146: Unknown type: int
  
### Reproducible Example
Example:
  ```r
tbl(con, "some_table") %>% 
  mutate(ci = '2019') %>% 
  mutate(ci = as.integer(ci))
```

This is fixed by replacing "INT" with "INTEGER" at
https://github.com/DyfanJones/RAthena/blob/45fc75361554d2b601f1629e12a603015680484f/R/sql_translate_env.R#L52

Also, I think the line
https://github.com/DyfanJones/RAthena/blob/45fc75361554d2b601f1629e12a603015680484f/R/DataTypes.R#L6
should be corrected.

**Comment by OssiLehtinen** [comment]
Ah, also the test at 
https://github.com/DyfanJones/RAthena/blob/45fc75361554d2b601f1629e12a603015680484f/tests/testthat/test-dplyr-sql-trans-env.R#L36
should have 'INTEGER' instead of 'INT'.

**Comment by DyfanJones** [comment]
The alias INT should be supported by AWS Athena:
https://docs.aws.amazon.com/athena/latest/ug/data-types.html#type-integer

**Comment by DyfanJones** [comment]
Class INT is tested in unit test: https://github.com/DyfanJones/RAthena/blob/master/tests/testthat/test-datatransfer.R

If there is an issue then it will be with the `sql_translate_env.R` as `DataTypes.R` passes all unit tests so far.

**Comment by DyfanJones** [comment]
Found the issue. This is down to how AWS Athena works:

>INT. Athena combines two different implementations of the INTEGER data type. In Data Definition Language (DDL) queries, Athena uses the INT data type. In all other queries, Athena uses the INTEGER data type, where INTEGER is represented as a 32-bit signed value in two's complement format, with a minimum value of-2^31 and a maximum value of 2^31-1. In the JDBC driver, INTEGER is returned, to ensure compatibility with business analytics applications. 

When casting it should be `cast(var1 as integer)` however for the DDL it should be `INT`. Believe this will be down to how AWS Athena jumps between HIVE DDL and Presto SQL Syntax

**Comment by OssiLehtinen** [comment]
Ah, OK, thanks for looking into it!

**Comment by DyfanJones** [comment]
`cast(var1 as integer)` has now been added to `sql_translate_env.R` with unit test updated accordingly. Going to use column_name branch to pull this bug fix.
