### ISSUE TITLE
mutate(as.character) produces an error (unknown type)

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/RAthena#45]
### Issue Description
Similar to the earlier issue with as.integer https://github.com/DyfanJones/RAthena/issues/42, as.character also produces an error, as 'string' is an unknown type. Here we should use 'varchar'.

### Reproducible Example

Example:
  ```r
library(RAthena)
library(DBI)
con <- dbConnect(RAthena::athena(),
                 profile_name = "rathena")

tbl(con, "iris")) %>%
  mutate(sepal_length = as.character(sepal_length))
```
> Error: SYNTAX_ERROR: line 1:8: Unknown type: string

Surely related again to the differences between HIVE DDL and Presto SQL Syntax.

**Comment by DyfanJones** [comment]
Thanks for point this out :) Apologies for this issue, I will fix this.

**Comment by DyfanJones** [comment]
This has now been fixed in latest dev version. Thanks for identifying bug 👍
