### ISSUE TITLE
Feature request: optionally delete data in S3 when doing dbRemoveTable

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/RAthena#48]
Executing "drop table" in Athena leaves the data in place.

However, sometimes the data in S3 is useless without the table definition (such as when generating temp-tables with  ... %>% compute()), and it would be convenient to delete data with the same call. 

The following definition of dbRemoveTable would accomplish this without interfering with 'normal' usage. There are some overrideable precautions built in to avoid accidental data loss (for example, if a table definition points to the root of bucket, everything there would get deleted).

What do you think?

```r

#' @rdname dbRemoveTable
#' @export
setMethod(
  "dbRemoveTable", c("AthenaConnection", "character"),
  function(conn, name, delete_data = FALSE, no_confirm = FALSE, ...) {
    if (!dbIsValid(conn)) {stop("Connection already closed.", call. = FALSE)}
    
    if(!grepl("\\.", name)) name <- paste(conn@info$dbms.name, name, sep = ".")
  
    if(delete_data)
    {
      nobjects <- 1000 # We get only 1000 objects at a time
      while(nobjects >= 1000) {
        if (grepl("\\.", name)) {
          dbms.name <- gsub("\\..*", "" , name)
          Table <- gsub(".*\\.", "" , name)
        } else {
          dbms.name <- conn@info$dbms.name
          Table <- name}
      
        glue <- conn@ptr$client("glue")
        tryCatch(
          s3_path <- split_s3_uri(glue$get_table(DatabaseName = dbms.name,
                                   Name = Table)$Table$StorageDescriptor$Location),
          error = function(e) py_error(e))
        
        s3 <- conn@ptr$client("s3")
        tryCatch(
          objects <- s3$list_objects(Bucket=s3_path$bucket, Prefix=s3_path$key),
          error = function(e) py_error(e))
        
        nobjects <- length(objects$Contents)
        
        all_keys <- sapply(objects$Contents, function(x) x$Key)
        
        message(paste0("Info: The following S3 objects will be deleted:\n", paste0(paste0("s3://", s3_path$bucket, all_keys), collapse="\n")))
        if(!no_confirm) {
          confirm <- readline(prompt = "Delete files (y/n)?: ")
          if(confirm != "y") {
            message("Info: Table deletion aborted.")
            return(NULL)
          }
          
        }
        
        # This could be done with s3$delte_objects in one command, but cannot figure out the syntax right now...
        for(c_object in all_keys){
          tryCatch(
            s3$delete_object(Bucket=s3_path$bucket, Key=c_object),
            error = function(e) py_error(e))
        }
      }
    }
    
    res <- dbExecute(conn, paste("DROP TABLE ", name, ";"))
    dbClearResult(res)
    if(!delete_data) message("Info: Only Athena table has been removed.")
    invisible(TRUE)
  })


```

**Comment by DyfanJones** [comment]
@OssiLehtinen Thanks for this. I was wondering how to get the table s3 location, but couldn't think of it from the top of my head. I will create a branch for this change. Plus I will check out the note you left in the comments.

**Comment by DyfanJones** [comment]
The creation of the s3 and glue objects could be taken out of the while loop to help with performance. I do like the prompt for delete files.

**Comment by DyfanJones** [comment]
Added pull request: https://github.com/DyfanJones/RAthena/pull/49

As this gives `dbRemoveTable` new features. Will need to check if other functions can be made simpler. Also need to design a new unit test to cater for the change. Thanks for this contribution.

I have done some very minor changes in the pull request please feel free to review

**Comment by DyfanJones** [comment]
This feature has now been added to the main branch. Please feel free to download new version from:
```
remotes::install_github("dyfanjones/rathena")
```

Will close this request.
