### ISSUE TITLE
Should vroom be used for read/write for extra speed?

### ISSUE THREAD

**Issue by DyfanJones** [DyfanJones/RAthena#56]
The package `vroom`: https://github.com/r-lib/vroom claims:
> The fastest delimited reader for R, 1.27 GB/sec.

Benchmark: https://vroom.r-lib.org/articles/benchmarks.html

When passing data to and from AWS Athena `vroom` has the potential to increase the performance with large files plus it offers a method to write `gzip` files in parrel:

```
vroom_write(mtcars, pipe("pigz > mtcars.tsv.gz"))
```
-----
Down side:

- Currently package is highly dependent on `data.table` i.e. data is generally return using `data.table`. Plus alot of data wrangling techniques use `data.table` for speed.
- There is a potential Rstudio version caveat:
> RStudio’s environment pane calls object.size() when it refreshes the pane, which for Altrep objects can be extremely slow. RStudio 1.2.1335+ includes the fixes (RStudio#4210, RStudio#4292) for this issue, so so it is recommended you use at least that version.
- Extra dependency

**Comment by OssiLehtinen** [comment]
Getting that kind of throughput would definitely be great!

As a side note: I've been using readr earlier for similar tasks and in my tests reading data has been some 30% faster than with data.table, but I don't think that kind of a speed up would warrant such an overhaul. Getting what vroom claims would be a different story, though.

Would it make any sense to give the user the option of choosing which backend to use? Default to data.table and use vroom if specifically instructed to do so (or use some environment variable or what not). Perhaps this would make things unnecessarily complicated?

**Comment by DyfanJones** [comment]
From my understanding data.table should be faster than readr for reading delimited files. However an option to set file parser could be an interesting solution. the only problem is that vroom currently has no plans to pass bigints into integer64. 

Final note: It would be good to create an option for file parser with out increasing the number of dependencies.

**Comment by DyfanJones** [comment]
Managed to build this feature in PR #62. This solution feels to be elegant and enables vroom to be an option file_parser. The positive thing about this method is that is allows other file_parser to be added.

**Comment by DyfanJones** [comment]
will build unit tests for vroom file_parser using data_transfer test

**Comment by DyfanJones** [comment]
PR #62 has passed all units tests. This feature has now been merged

**Comment by OssiLehtinen** [comment]
Awesome, reading is fast with vroom!

**Comment by DyfanJones** [comment]
The good thing about this implementation is that it can easily be extended to utilise other file pasrers I.e. readr. It even can be extended to read out of memory queries using disk.frame. However I am pretty happy with this initial implementation :)
