### ISSUE TITLE
paste not translated correctly

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/RAthena#65]
### Issue Description
Doing something like 

```r
tbl(con, "table) %>% mutate(new_col = paste(col1, col2))
```
fails with an error about a missing fucntion (concat_ws).

I think we need to add paste (and paste0) to sql_translate_env's athtena specific translations. 

Adding lines:

```r 
      paste = sql_prefix("CONCAT"),
      paste0 = sql_prefix("CONCAT"),
```

to sql_translator under sql_translate_env.AthenaConnection should do the trick.

**Comment by DyfanJones** [comment]
Currently on holiday, will look into this when I am back :)

**Comment by OssiLehtinen** [comment]
Have a good one!

**Comment by DyfanJones** [comment]
The problem with `concat` for paste, is that is doesn't offer a different value for `sep`. For `paste0` this would work perfectly :D

**Comment by DyfanJones** [comment]
Should be able to support paste with option to change `sep` the helper function:
```
athena_paste <- function(..., sep = " ", con) {
  escape <- pkg_method("escape", "dbplyr")
  sql <- pkg_method("sql", "dplyr")
  sep <- paste0('||', sep, '||')
  pieces <- vapply(list(...), escape, con = con,collapse = sep, character(1))
  sql(paste(pieces))
}
```

**Comment by DyfanJones** [comment]
PR #66 seems to be fixed paste issue with athena
