### ISSUE TITLE
tbl %>% compute(name="test.table") tries to return a tbl-pointer for, e.g., "default.test.table"

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/RAthena#74]
### Issue Description

Doing something like the following:

```r
tbl(con, "table1") %>%
  compute(name = "test.table")
```

will result in an error, such as:
>  Error: SYNTAX_ERROR: line 2:6: Table awsdatacatalog.default.test.table does not exist 

The command does produce the table 'table' in database 'test', but compute tries to a table  in the 'default' database (or which every you have set when connecting to Athena) named 'test.table'

**Comment by DyfanJones** [comment]
Sorry about this, I think this is due to the `compute` method in `dbplyr`. When the table has been created in Athena `dbplyr:compute` calls the following:
```
tbl(x$src, name) %>%
    group_by(!!! syms(op_grps(x))) %>%
    add_op_order(op_sort(x))
```
Which means it will be looking for a table called "test.table".  have you tried changing your connection to:

```
library(DBI)
library(dplyr)

con <- dbConnect(RAthena::athena(), schema_name = "test")

tbl(con, "table1") %>%
  compute(name = "table")
```

**Comment by DyfanJones** [comment]
Managed to create a solution that doesn't mean a rebuild of the `dbplyr::compute` method. Please check out PR#72

```
library(DBI)
library(dplyr)

# connecting to default schema
con <- dbConnect(RAthena::athena())

# writing temp schema
tbl(con, "iris") %>%
  compute(name = "temp.iris")
```

**Note:** This feature is different than alot of other DBI packages that integrate with dplyr. They will return your above error.

**Comment by OssiLehtinen** [comment]
Alright, the fix in PR #72 seems to do it.

I agree this is a bit of a deviation from the 'standard', but don't see an immediate issue with it. One can still use %>% compute(name = in_schema("schema", "table")) as usual and things work ok.

**Comment by DyfanJones** [comment]
Closing issue, if you find anything else please raise a ticket and i will try to get it in before the next cran release

**Comment by DyfanJones** [comment]
These change have been pushed to cran
